server:
  port: 8765

logging:
  level:
    root: info


spring:
  profiles:
    active: dev

  application:
    name: lisiService

  cloud:
    config:

      label: master
      profile: dev
      uri: http://localhost:8091/
